### PR TITLE
updated iOS, market and splash screen, supports larger phones

### PR DESCRIPTION
**Pull request by adamcleavey**
finally got to sit down and to this. pls build and see what you think on iOS

### CODE REVIEW

**Comment by j-ro** [comment]
nice, will try it out when I can. Did you test on android? In the past, when updating cordova, I've had issues with android sometimes.

**Comment by adamcleavey** [comment]
No, have not tested on android yet.  Don’t have a device.

**Comment by j-ro** [comment]
I do, but I typically do initial testing in the simulator, with this: https://www.genymotion.com/

free for personal use

**Comment by j-ro** [comment]
so, moved to cordova 6.0, or trying to. Trying android now. But iOS does seem to be working better. See this repo, which is now just the www files, and give it a try! https://github.com/j-ro/BusTrackDC

Going to need the mapkit plugin here too: https://github.com/j-ro/Cordova-MapKit

Plus these plugins:

cordova-plugin-google-analytics
cordova-plugin-googleplayservices
ionic-plugin-keyboard
cordova-plugin-device
cordova-plugin-dialogs
cordova-plugin-geolocation
cordova-plugin-splashscreen
cordova-plugin-console

**Pull request closed without merging**
